### ISSUE TITLE
Invalid distribution

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-anchornav#15]
Latest release of `0.1.9` is not there in distribution https://github.com/interactive-pioneers/iptools-jquery-anchornav/blob/master/dist/iptools-jquery-anchornav.min.js#L1

**Comment by beroes** [comment]
I can see it is there @ain

**Comment by ain** [comment]
Yes, for the last 9 minutes. But in `0.1.9` release, minified distribution was that of version `0.1.5`.

Please always compile distribution right after bumping the version and before tagging a release. 

We need to release `0.1.10` that __is not a breaking change__ and delivers correct minified version at `/dist`.
