### ISSUE TITLE
Setting showHideNavAt does not have any effect

### ISSUE THREAD

**Issue by davleh** [interactive-pioneers/iptools-jquery-anchornav#22]
The setting showHideNavAt is overwritten by `this.settings.showHideNavAt = $(this.settings.selectors.header).height();` in line 70 and thus does not have any effect.

It would be good to have such an option.

**Comment by beroes** [comment]
Good point, @davleh , I will fix this today.

**Comment by davleh** [comment]
Thanks! :) It would ne nice if you could also update the documentation.
