### ISSUE TITLE
provide a destroy method

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-anchornav#4]
Provide a destroy method that removes at least plugin data and event listeners.

example:
```javascript
destroy: function() {
  this.$element.off('click' + this.settings.eventNamespace, '.' + cssClassTrigger);
  this.$element.removeData('plugin_' + pluginName);
}
```

edit: Add param to removeData method to ensure that only plugin related attributes are removed.

**Comment by ain** [comment]
:+1:

**Comment by beroes** [comment]
fad768e568568e048f489c7ec4d1e755b7e68062
