### ISSUE TITLE
use scss instead of css

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-anchornav#8]
Let's use scss for style definition and render css output to ./dist.
grunt task + scss linter see:
https://github.com/interactive-pioneers/iptools-jquery-genericfilter

**Comment by ain** [comment]
Why? We're having a generic component that people could use with SCSS, CSS or LESS. Any clear benefits?

**Comment by GeorgMeyer23** [comment]
good point, closed.

**Comment by ain** [comment]
Nevertheless there is a question of whether or not CSS should be in distribution? But of course a separate topic.
